test signing

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -34,3 +34,8 @@ jobs:
         run: | 
           git rev-parse --abbrev-ref HEAD
           git log --no-decorate --show-signature -n 1
+          export RETURN_VALUE="$?"
+          if [ "$RETURN_VALUE" -ne 0 ]; then
+            echo "PR checks are incomplete or have failed"
+            exit 1
+          fi
