test signing

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -43,3 +43,21 @@ jobs:
             exit 1
           fi
           echo "success"
+
+  verify:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: verify
+        run: |
+          git pull
+          git remote update
+          git rev-parse --abbrev-ref HEAD
+          git log --graph --abbrev-commit --no-decorate -n 1 --show-signature origin/release-${{ github.run_id }}
+          export COMMIT_LOG=$(git log --graph --abbrev-commit --no-decorate -n 1 --show-signature origin/release-${{ github.run_id }})
+          export SUB="failed to parse signature"
+          if [[ "$STR" == *"$SUB"* ]]; then
+            echo "Failed to validate signature"
+            exit 1
+          fi
+          echo "success"
