using GH to test verification

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -31,22 +31,32 @@ jobs:
             --field branch="$DESTINATION_BRANCH" \
             --field sha="$SHA"
 
-  verify:
-    needs: [create-branch]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: verify
-        run: |
-          git pull
-          git remote update
-          git rev-parse --abbrev-ref HEAD
-          git log --graph --abbrev-commit --no-decorate -n 1 --show-signature origin/release-${{ github.run_id }}
-          export COMMIT_LOG=$(git log --graph --abbrev-commit --no-decorate -n 1 --show-signature origin/release-${{ github.run_id }})
-          export SUB="failed to parse signature"
-          export SUBTWO="Can't check signature"
-          if [[ "$COMMIT_LOG" == *"$SUB"* || "$COMMIT_LOG" == *"$SUBTWO"* ]]; then
-            echo "Failed to validate signature"
-            exit 1
-          fi
-          echo "success"
+    verify:
+      needs: [create-branch]
+      runs-on: ubuntu-latest
+      steps:
+        - uses: actions/checkout@v3
+        - name: verify
+          run: gh api --method GET /repos/:owner/:repo/commits/release-${{ github.run_id }} | | jq '.commit.verification.verified'
+          env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+#  verify:
+#    needs: [create-branch]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: verify
+#        run: |
+#          git pull
+#          git remote update
+#          git rev-parse --abbrev-ref HEAD
+#          git log --graph --abbrev-commit --no-decorate -n 1 --show-signature origin/release-${{ github.run_id }}
+#          export COMMIT_LOG=$(git log --graph --abbrev-commit --no-decorate -n 1 --show-signature origin/release-${{ github.run_id }})
+#          export SUB="failed to parse signature"
+#          export SUBTWO="Can't check signature"
+#          if [[ "$COMMIT_LOG" == *"$SUB"* || "$COMMIT_LOG" == *"$SUBTWO"* ]]; then
+#            echo "Failed to validate signature"
+#            exit 1
+#          fi
+#          echo "success"
